# Read the Docs configuration for macpymessenger
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build environment configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.14"  # Match project requirements (Python 3.14+)
    rust: "1.75"    # Required for building dependencies

# Sphinx documentation builder
sphinx:
  configuration: docs/conf.py  # Path to Sphinx config

# Output formats
formats:
  - pdf  # Generate PDF documentation
  # - epub  # Uncomment to generate ePub format